# no version needed since 2020

services:
  jekyll:
    build: .
    environment:
      - JEKYLL_ENV=local
    command: bundle exec jekyll serve --host 0.0.0.0 --force_polling --config _config.yml,_config_dev.yml
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    ports:
      - '4000:4000'

volumes:
  bundle_cache:
